### ISSUE TITLE
[Suggestion] Auto Hide missions.

### ISSUE THREAD

**Issue by jordan8396** [LSS-Manager/lss-manager-v3#795] opened 2020-09-01 05:45 UTC
Hi, I'd like to propose a new module which incorporates (or mimics) the actions of a script/code with which you can choose to collapse or complete hide red and green missions. I know that there's already the "MISSIONOUT" module, but this only collapses the missions rather than completely hiding them as the suggested script does.
The original script's code is at [/MisteryMan/autohidemissions](https://github.com/MisteryMan/autohidemissions).

**Comment by KBOE2** [comment] 2020-09-01 05:46
Close as duplicate of #537

**Closed by KBOE2** 2020-09-01 05:46 UTC

**Comment by jordan8396** [comment] 2020-09-01 05:49
Oh Sorry! didn't realise it was suggested in there.

**Comment by KBOE2** [comment] 2020-09-01 05:49
No problem. Is also not that easy to detect, as I wrote it in german 😅
